bind-key  j  select-pane -D
bind-key  k  select-pane -U
bind-key  h  select-pane -L
bind-key  l  select-pane -R

bind-key  c  new-window   -c "#{pane_current_path}"
bind-key  %  split-window -c "#{pane_current_path}" -h
bind-key '"' split-window -c "#{pane_current_path}" -v

setw -g mode-keys vi

set -g status-right "bat:#(cat /sys/class/power_supply/BAT0/capacity || echo '--')% cpu:#(mpstat | grep all | awk '{print 100 - int($13)}')% mem:#(echo $(( `free | grep 'Mem' | awk '{printf $3}'` * 100 / `free | grep 'Mem' | awk '{printf $2}'` )))% @#(uname -n) %H:%M#(timedatectl | grep Local | awk '{printf $6}' | tr 'A-Z' 'a-z')"
set -g status-right-length 64
